# Generated by Django 3.1.4 on 2021-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depotstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_in', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matatuinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6, null=True)),
                ('passengers', models.IntegerField(null=True)),
                ('destination', models.CharField(max_length=150, null=True)),
                ('currentLocation', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passengerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passDestination', models.CharField(max_length=150, null=True)),
                ('passLocation', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
