# Generated by Django 3.1.4 on 2021-01-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_auto_20210106_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matatuinfo',
            old_name='passengers',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='matatuinfo',
            name='FullOccupancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matatuinfo',
            name='plate',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
