# Generated by Django 3.1.4 on 2021-01-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_auto_20210106_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routedestinations',
            options={'ordering': ['to_PlaceName'], 'verbose_name_plural': 'RouteDestinations'},
        ),
        migrations.RenameField(
            model_name='routedestinations',
            old_name='PlaceName',
            new_name='from_PlaceName',
        ),
        migrations.AddField(
            model_name='routedestinations',
            name='to_PlaceName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
