# Generated by Django 3.1.4 on 2021-01-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0005_auto_20210106_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='matatuinfo',
            name='departureTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Driverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=250, null=True)),
                ('driverSchedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.routedestinations')),
                ('driverVehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.matatuinfo')),
            ],
            options={
                'verbose_name_plural': 'Driverinfo',
                'ordering': ['driverName'],
            },
        ),
    ]
