# Generated by Django 3.1.4 on 2021-01-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0006_auto_20210108_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotstage',
            name='MatatusAssigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.matatuinfo'),
        ),
    ]
