# Generated by Django 3.1.4 on 2021-01-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0007_depotstage_matatusassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotstage',
            name='depotdestinations',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.routedestinations'),
        ),
    ]
