# Generated by Django 3.1.4 on 2021-01-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0008_auto_20210109_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depotstage',
            name='depotdestinations',
        ),
        migrations.AddField(
            model_name='routedestinations',
            name='boardDepot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.depotstage'),
        ),
    ]
