# Generated by Django 3.1.4 on 2021-01-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0009_auto_20210109_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depotstage',
            name='MatatusAssigned',
        ),
        migrations.AddField(
            model_name='depotstage',
            name='depotLocation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='matatuinfo',
            name='boardingStage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.depotstage'),
        ),
    ]
