# Generated by Django 3.1.4 on 2021-01-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0010_auto_20210109_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matatuinfo',
            name='boardingStage',
        ),
        migrations.RemoveField(
            model_name='matatuinfo',
            name='destination',
        ),
        migrations.AddField(
            model_name='matatuinfo',
            name='Voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trial.routedestinations'),
        ),
        migrations.AlterField(
            model_name='matatuinfo',
            name='currentLocation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
