# Generated by Django 3.1.4 on 2021-01-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0011_auto_20210117_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matatuinfo',
            name='Voyage',
        ),
        migrations.AddField(
            model_name='matatuinfo',
            name='Voyage',
            field=models.ManyToManyField(to='trial.RouteDestinations'),
        ),
    ]
