# Generated by Django 3.1.4 on 2021-02-09 11:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0013_auto_20210117_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotstage',
            name='depotLocation',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
