# Generated by Django 3.1.4 on 2021-02-10 08:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0015_auto_20210210_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matatuinfo',
            name='currentLocation',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='passDestination',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='passengerinfo',
            name='passLocation',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='routedestinations',
            name='from_PlaceName',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='routedestinations',
            name='to_PlaceName',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
