# Generated by Django 3.1.4 on 2021-02-10 09:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0016_auto_20210210_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='routedestinations',
            name='from_Place',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='routedestinations',
            name='to_Place',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='routedestinations',
            name='from_PlaceName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routedestinations',
            name='to_PlaceName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
