# Generated by Django 3.1.4 on 2021-02-12 10:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0017_auto_20210210_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenroad_id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=104000)),
            ],
            options={
                'verbose_name_plural': 'Roads',
            },
        ),
    ]
