# Generated by Django 3.1.4 on 2021-02-15 11:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0018_roads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roads',
            name='kenroad_id',
        ),
        migrations.AddField(
            model_name='roads',
            name='country',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='curntprac',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='fclass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='gnralspeed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='iselevated',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='iso3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='isseasonal',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='last_updat',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='notes',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='ntlclass',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='numlanes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='onme',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='osm_id',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='rdwidthm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='rtenme',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='sourceid',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='srfcond',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='srftpe',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='status',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='roads',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
        migrations.AlterField(
            model_name='roads',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
