# Generated by Django 3.1.7 on 2021-03-05 04:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0020_auto_20210304_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainroads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenroad_id', models.BigIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4237)),
            ],
            options={
                'verbose_name_plural': 'Mainroads',
            },
        ),
    ]
