# Generated by Django 3.1.7 on 2021-03-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0022_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mainroads',
        ),
    ]
